Repository ku-kim/issue-tracker, pull requests merged in 2022-06, with the labels that each got.

#6 [BE] Spring 프로젝트 세팅
  be/.gitignore
  be/build.gradle
  be/gradle/wrapper/gradle-wrapper.jar
  be/gradle/wrapper/gradle-wrapper.properties
  be/gradlew
  be/gradlew.bat
  be/settings.gradle
  be/src/main/java/dev/kukim/issues/IssuesApplication.java
  be/src/main/resources/application.yml
  be/src/test/java/dev/kukim/issues/IssuesApplicationTests.java
Labels: 📦️ package, 🏗️ build, 🤖 BE

#9 [공통] FE 배포 아키텍처, Github Actions 스크립트
  .github/workflows/front-deploy.yaml
Labels: 🏗️ build, 🌐 FE

#22 [BE] PR 리뷰 적용 : Graceful shutdown, logback, spring boot 2.7.0->2.6.7
  .github/workflows/back-deploy.yaml
  be/build.gradle
  be/deploy.sh
  be/src/main/resources/application-local.yml
  be/src/main/resources/application-prod.yml
  be/src/main/resources/application.yml
  be/src/main/resources/logback-spring.xml
Labels: ✨ feature, 🏗️ build, 🤖 BE

#24 [FE] 공통적으로 사용되는 폰트, 색상 모듈화
  fe/package.json
  fe/src/styles/color.ts
  fe/src/styles/font.ts
Labels: 💄 style, 🌐 FE

#26 [FE] @typescript-eslint/parser 오류 해결, styled-components 설치
  fe/package-lock.json
  fe/package.json
Labels: 🐛 bug, 📦️ package, 🌐 FE

#34 [FE] Avatar 컴포넌트 리팩토링
  fe/src/components/common/Avatar.tsx
  fe/src/pages/Template.tsx
Labels: ♻️ refactor, 🌐 FE

#35 [BE] 로그인 기능 인터셉터 구현과 테스트 코드
  be/build.gradle
  be/src/main/java/dev/kukim/issues/config/WebMvcConfig.java
  be/src/main/java/dev/kukim/issues/error/controller/exceptionControllerAdvice.java
  be/src/main/java/dev/kukim/issues/error/controller/response/ErrorResponse.java
  be/src/main/java/dev/kukim/issues/user/auth/controller/LoginInterceptor.java
  be/src/main/java/dev/kukim/issues/user/auth/controller/response/GithubUserResponse.java
  be/src/main/java/dev/kukim/issues/user/auth/exception/AuthorizationException.java
  be/src/main/java/dev/kukim/issues/user/auth/service/LoginService.java
  be/src/main/java/dev/kukim/issues/user/auth/service/LoginTokenGenerator.java
  be/src/main/java/dev/kukim/issues/user/user/domain/User.java
  be/src/main/resources/logback-spring.xml
  be/src/test/java/dev/kukim/issues/IssuesApplicationTests.java
  be/src/test/java/dev/kukim/issues/MysqlTestContainer.java
  be/src/test/java/dev/kukim/issues/user/auth/controller/LoginAcceptanceTest.java
  be/src/test/java/dev/kukim/issues/user/auth/service/LoginServiceTest.java
  be/src/test/resources/application.yml
Labels: 🐛 bug, ✨ feature, 🤖 BE

#42 [FE] LinearGraph 컴포넌트 구현 및 Template 작업
  fe/src/components/common/LinearGraph.tsx
  fe/src/pages/Template.tsx
  fe/src/styles/size.ts
Labels: ✨ feature, 🌐 FE

#43 [FE] IssueHader 컴포넌트 생성
  fe/src/components/IssueHeader.tsx
  fe/src/components/common/Header.tsx
  fe/src/pages/IssueList.tsx
  fe/src/pages/LabelList.tsx
Labels: ✨ feature, 🌐 FE

#44 [FE] components 하위 폴더 구조 변경
  fe/src/components/IssueDetail/IssueLabel.tsx
  fe/src/components/IssueList/Checkbox.tsx
  fe/src/components/IssueList/FilterBar.tsx
  fe/src/components/IssueList/IssueHeader.tsx
  fe/src/components/IssueList/IssueItem.tsx
  fe/src/components/LabelList/LabelItem.tsx
  fe/src/components/common/SubNav.tsx
  fe/src/pages/IssueList.tsx
  fe/src/pages/LabelList.tsx
  fe/src/pages/Template.tsx
Labels: 🌐 FE

#46 [FE] 모달 구현
  fe/src/components/IssueList/FilterBar.tsx
  fe/src/components/IssueList/IssueHeader.tsx
  fe/src/components/common/DropdownBtn.tsx
  fe/src/components/common/Modal.tsx
  fe/src/pages/IssueList.tsx
  fe/src/pages/LabelList.tsx
  fe/src/styles/zIndex.ts
Labels: ✨ feature, 🌐 FE

#50 [FE] Errorboundary 생성
  fe/src/components/ErrorBoundary.tsx
Labels: ✨ feature, 🌐 FE

#53 [FE] useFetch dependency 오류 해결
  fe/src/hooks/useFetch.tsx
Labels: 🐛 bug, 🌐 FE
